---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Getting started: Webhook Example"
      solveButton: false
    - name: module-02
      label: "Getting started: Kafka Example"
      solveButton: false
    - name: module-03
      label: "Getting started: URL Check Example"
      solveButton: false

tabs:
  - name: VSCode Editor
    url: https://control-${guid}.${domain}/editor/?folder=/home/rhel/

  # - name: Cloud (PoC)
  #   url: /cloud
